# Generated by Django 5.2.8 on 2025-11-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'agents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('agent_id', models.IntegerField(primary_key=True, serialize=False)),
                ('daily_caps', models.IntegerField()),
                ('weekly_caps', models.IntegerField()),
            ],
            options={
                'db_table': 'agent_settings',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=255)),
                ('appointment_time', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'appointments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_id', models.IntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'calendar_events',
                'managed': True,
            },
        ),
    ]
