# Generated by Django 5.2.8 on 2025-11-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='agentsettings',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'managed': False},
        ),
    ]
