# Generated by Django 5.2.8 on 2025-11-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_agent_options_alter_agentsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(db_index=True)),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_email', models.EmailField(max_length=254)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField()),
                ('datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'available_timeslots',
                'indexes': [models.Index(fields=['agent_id', 'date'], name='available_t_agent_i_2c8d89_idx'), models.Index(fields=['datetime'], name='available_t_datetim_eef98c_idx'), models.Index(fields=['date'], name='available_t_date_bf985d_idx')],
                'unique_together': {('agent_id', 'datetime')},
            },
        ),
    ]
