# Generated by Django 5.2.8 on 2025-11-10 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_availabletimeslot'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='availabletimeslot',
            name='available_t_date_bf985d_idx',
        ),
    ]
